import type { Locale } from "@/lib/locale";

export const strings: Record<Locale, {
  nav: Record<"home" | "about" | "projects" | "blog" | "shop" | "playground" | "contact", string>;
  common: Record<"readMore" | "backToArticles" | "addToCart" | "subscribe" | "submit" | "myAccount" | "login" | "cart" | "openMenu" | "closeMenu", string>;
  footer: Record<"tagline" | "navigate" | "newsletterHeading" | "newsletterBody" | "copyright" | "builtWith", string>;
  newsletter: Record<"placeholder" | "subscribing" | "success" | "duplicate" | "error", string>;
  projects: Record<"heading" | "unavailable" | "loadMore" | "close" | "noDescription" | "languages" | "tags" | "none" | "created" | "updated" | "viewOnGitHub", string>;
  playground: Record<"tooltip", string>;
  hero: Record<"alt", string>;
  meta: Record<"homeDescription" | "blogDescription", string>;
  blog: Record<"heading" | "noPosts" | "readMore" | "backToArticles" | "dateLocale", string>;
  contact: Record<"heading" | "imageAlt" | "descriptionMeta", string>;
  form: Record<"name" | "email" | "message" | "sending" | "send" | "success" | "error", string>;
  shop: Record<"heading" | "subheading" | "noProducts" | "free" | "descriptionMeta" | "comingSoon", string>;
  cart: Record<"heading" | "empty" | "backToShop" | "remove" | "total" | "continueShopping" | "redirecting" | "checkout" | "descriptionMeta", string>;
  success: Record<"heading" | "confirmedLoggedIn" | "confirmedGuest" | "noDownloads" | "download" | "comingSoon" | "accessHeading" | "accessBody" | "createAccount" | "login" | "backToShop" | "descriptionMeta", string>;
  product: Record<"free" | "inCart" | "added" | "addToCart", string>;
  account: Record<"loginHeading" | "registerHeading" | "dashboardHeading" | "settingsHeading" |
    "forgotHeading" | "resetHeading" | "invalidLinkHeading" | "invalidLinkBody" |
    "email" | "password" | "name" | "currentPassword" | "newPassword" |
    "minChars" | "changePassword" | "loggingIn" | "login" | "forgotPassword" |
    "noAccount" | "register" | "alreadyAccount" | "creatingAccount" | "createAccount" |
    "myDownloads" | "noPurchases" | "visitShop" | "download" | "comingSoon" |
    "appSubscriptions" | "appSubscriptionsBody" | "settings" | "logout" |
    "backToDashboard" | "saving" | "saveChanges" | "changesSaved" |
    "sending" | "sendResetLink" | "resetSent" | "backToLogin" |
    "resetHeadingInvalid" | "requestNewLink" | "resetting" | "setNewPassword" |
    "passwordUpdated" | "tryAgain" | "somethingWrong",
    string>;
}> = {
  de: {
    nav: {
      home: "Home",
      about: "Über mich",
      projects: "Projekte",
      blog: "Blog",
      shop: "Shop",
      playground: "Playground",
      contact: "Kontakt",
    },
    common: {
      readMore: "Weiterlesen →",
      backToArticles: "← Alle Artikel",
      addToCart: "In den Warenkorb",
      subscribe: "Abonnieren",
      submit: "Senden",
      myAccount: "Mein Konto",
      login: "Anmelden",
      cart: "Warenkorb",
      openMenu: "Menü öffnen",
      closeMenu: "Menü schließen",
    },
    footer: {
      tagline: "Frontend Web- & App-Entwicklung aus Hamburg — Code trifft Kunst.",
      navigate: "Navigation",
      newsletterHeading: "Bleib auf dem Laufenden",
      newsletterBody: "Gelegentliche Updates über Projekte und Neuigkeiten aus dem Studio.",
      copyright: "Alle Rechte vorbehalten.",
      builtWith: "Gebaut mit Next.js · Gehostet auf Vercel",
    },
    newsletter: {
      placeholder: "deine@email.de",
      subscribing: "...",
      success: "Du bist dabei — willkommen!",
      duplicate: "Du bist bereits angemeldet.",
      error: "Etwas ist schiefgelaufen — bitte versuch es erneut.",
    },
    projects: {
      heading: "Projekte",
      unavailable: "Projekte gerade nicht verfügbar — schau bald wieder vorbei.",
      loadMore: "Mehr laden",
      close: "Schließen",
      noDescription: "Keine Beschreibung vorhanden.",
      languages: "Sprachen",
      tags: "Tags",
      none: "keine",
      created: "Erstellt",
      updated: "Aktualisiert",
      viewOnGitHub: "Auf GitHub ansehen ↗",
    },
    playground: {
      tooltip: "Schreib ein Gedicht",
    },
    hero: {
      alt: "Studio Mitsch — Webentwicklerin & App-Entwicklerin aus Hamburg",
    },
    meta: {
      homeDescription: "Portfolio von Miriam Schwartz — Fullstack-Entwicklerin aus Hamburg. Webentwicklung mit React & Next.js, App-Entwicklung mit Flutter & Dart.",
      blogDescription: "Gedanken über das Zusammenspiel von Webentwicklung und Design, wo Code auf Gestaltung trifft — von Miriam Schwartz.",
    },
    blog: {
      heading: "Blog",
      noPosts: "Noch keine Beiträge — schau bald wieder vorbei.",
      readMore: "Weiterlesen →",
      backToArticles: "← Alle Artikel",
      dateLocale: "de-DE",
    },
    contact: {
      heading: "Kontakt",
      imageAlt: "Kontakt — Studio Mitsch",
      descriptionMeta: "Nimm Kontakt mit Miriam Schwartz auf — für Freelance-Projekte in Web- und App-Entwicklung.",
    },
    form: {
      name: "Name",
      email: "E-Mail",
      message: "Nachricht",
      sending: "Wird gesendet...",
      send: "Nachricht senden",
      success: "Danke — ich melde mich bald bei dir.",
      error: "Etwas ist schiefgelaufen. Bitte versuch es erneut.",
    },
    shop: {
      heading: "Shop",
      subheading: "Kostenlose Downloads — bald kommt noch mehr!",
      noProducts: "Noch keine Produkte — schau bald wieder vorbei.",
      free: "Kostenlos",
      comingSoon: "Coming Soon",
      descriptionMeta: "Kunst & Tools von Miriam Schwartz — Studio Mitsch.",
    },
    cart: {
      heading: "Warenkorb",
      empty: "Dein Warenkorb ist leer.",
      backToShop: "← Zurück zum Shop",
      remove: "Entfernen",
      total: "Gesamt",
      continueShopping: "← Weiter einkaufen",
      redirecting: "Weiterleitung...",
      checkout: "Zur Kasse",
      descriptionMeta: "Dein Warenkorb — Studio Mitsch.",
    },
    success: {
      heading: "Danke!",
      confirmedLoggedIn: "Deine Bestellung ist bestätigt. Lade deine Dateien unten herunter — sie sind auch jederzeit in deinem Konto verfügbar.",
      confirmedGuest: "Deine Bestellung ist bestätigt. Lade deine Dateien unten herunter — die Links sind 7 Tage gültig.",
      noDownloads: "Keine Downloads gefunden.",
      download: "Herunterladen",
      comingSoon: "Coming Soon",
      accessHeading: "Jederzeit auf deine Downloads zugreifen",
      accessBody: "Deine Download-Links laufen nach 7 Tagen ab. Erstelle ein kostenloses Konto, um jederzeit auf deine Käufe zuzugreifen.",
      createAccount: "Konto erstellen",
      login: "Anmelden",
      backToShop: "← Zurück zum Shop",
      descriptionMeta: "Deine Bestellung ist bestätigt — dein Download ist bereit.",
    },
    product: {
      free: "Kostenlos",
      inCart: "Im Warenkorb",
      added: "Hinzugefügt!",
      addToCart: "In den Warenkorb",
    },
    account: {
      loginHeading: "Anmelden",
      registerHeading: "Registrieren",
      dashboardHeading: "Mein Konto",
      settingsHeading: "Kontoeinstellungen",
      forgotHeading: "Passwort vergessen",
      resetHeading: "Passwort zurücksetzen",
      invalidLinkHeading: "Ungültiger Link",
      invalidLinkBody: "Dieser Link ist ungültig oder abgelaufen.",
      email: "E-Mail",
      password: "Passwort",
      name: "Name",
      currentPassword: "Aktuelles Passwort",
      newPassword: "Neues Passwort",
      minChars: "Mindestens 8 Zeichen",
      changePassword: "Passwort ändern (optional)",
      loggingIn: "Anmelden...",
      login: "Anmelden",
      forgotPassword: "Passwort vergessen?",
      noAccount: "Noch kein Konto?",
      register: "Registrieren",
      alreadyAccount: "Bereits ein Konto?",
      creatingAccount: "Konto wird erstellt...",
      createAccount: "Konto erstellen",
      myDownloads: "Meine Downloads",
      noPurchases: "Noch keine Käufe.",
      visitShop: "Zum Shop →",
      download: "Herunterladen",
      comingSoon: "Demnächst",
      appSubscriptions: "App-Abonnements",
      appSubscriptionsBody: "App-Abonnements werden direkt über den App Store oder Google Play verwaltet. Besuche den Store, über den du die App gekauft hast, um dein Abo zu verwalten oder zu kündigen.",
      settings: "Einstellungen",
      logout: "Abmelden",
      backToDashboard: "← Zurück zum Dashboard",
      saving: "Speichern...",
      saveChanges: "Änderungen speichern",
      changesSaved: "Änderungen gespeichert.",
      sending: "Wird gesendet...",
      sendResetLink: "Reset-Link senden",
      resetSent: "Falls ein Konto für diese E-Mail existiert, erhältst du in Kürze einen Link. Schau in dein Postfach.",
      backToLogin: "← Zurück zur Anmeldung",
      resetting: "Speichern...",
      setNewPassword: "Neues Passwort setzen",
      passwordUpdated: "Passwort aktualisiert — du wirst weitergeleitet...",
      requestNewLink: "Neuen Link anfordern →",
      tryAgain: "Bitte versuch es erneut.",
      somethingWrong: "Etwas ist schiefgelaufen — bitte versuch es erneut.",
      resetHeadingInvalid: "Ungültiger Link",
    },
  },
  en: {
    nav: {
      home: "Home",
      about: "About",
      projects: "Projects",
      blog: "Blog",
      shop: "Shop",
      playground: "Playground",
      contact: "Contact",
    },
    common: {
      readMore: "Read more →",
      backToArticles: "← All Articles",
      addToCart: "Add to Cart",
      subscribe: "Subscribe",
      submit: "Send",
      myAccount: "My Account",
      login: "Login",
      cart: "Cart",
      openMenu: "Open Menu",
      closeMenu: "Close Menu",
    },
    footer: {
      tagline: "Frontend web & app development from Hamburg — where code meets craft.",
      navigate: "Navigate",
      newsletterHeading: "Stay in the loop",
      newsletterBody: "Occasional updates on projects and news from my studio.",
      copyright: "All rights reserved.",
      builtWith: "Built with Next.js · Deployed on Vercel",
    },
    newsletter: {
      placeholder: "your@email.com",
      subscribing: "...",
      success: "You're in — welcome!",
      duplicate: "You're already subscribed.",
      error: "Something went wrong — try again.",
    },
    projects: {
      heading: "Projects",
      unavailable: "Projects unavailable right now — check back soon.",
      loadMore: "Load More",
      close: "Close",
      noDescription: "No description available.",
      languages: "Languages",
      tags: "Tags",
      none: "none",
      created: "Created",
      updated: "Updated",
      viewOnGitHub: "View on GitHub ↗",
    },
    playground: {
      tooltip: "Write a poem",
    },
    hero: {
      alt: "Studio Mitsch — Hamburg based web and app developer",
    },
    meta: {
      homeDescription: "Portfolio of Miriam Schwartz — fullstack developer and app developer based in Hamburg. Web development with React & Next.js, app development with Flutter & Dart.",
      blogDescription: "Thoughts on web development, design, and the space where code meets craft — by Miriam Schwartz.",
    },
    blog: {
      heading: "Blog",
      noPosts: "No posts yet — check back soon.",
      readMore: "Read more →",
      backToArticles: "← All Articles",
      dateLocale: "en-GB",
    },
    contact: {
      heading: "Contact",
      imageAlt: "Contact — Studio Mitsch",
      descriptionMeta: "Get in touch with Miriam Schwartz for freelance web and app development projects.",
    },
    form: {
      name: "Name",
      email: "Email",
      message: "Message",
      sending: "Sending...",
      send: "Send Message",
      success: "Thank you — I'll get back to you soon.",
      error: "Something went wrong. Please try again.",
    },
    shop: {
      heading: "Shop",
      subheading: "Free downloads — more to come.",
      noProducts: "No products yet — check back soon.",
      free: "Free",
      comingSoon: "Coming soon",
      descriptionMeta: "Download art & tools by Miriam Schwartz — Studio Mitsch.",
    },
    cart: {
      heading: "Cart",
      empty: "Your cart is empty.",
      backToShop: "← Back to shop",
      remove: "Remove",
      total: "Total",
      continueShopping: "← Continue shopping",
      redirecting: "Redirecting...",
      checkout: "Checkout",
      descriptionMeta: "Your cart — Studio Mitsch.",
    },
    success: {
      heading: "Thank you!",
      confirmedLoggedIn: "Your order is confirmed. Download your files below. They'll also be available in your account dashboard.",
      confirmedGuest: "Your order is confirmed. Download your files below — links are valid for 7 days.",
      noDownloads: "No downloads found.",
      download: "Download",
      comingSoon: "Coming soon",
      accessHeading: "Access your downloads anytime",
      accessBody: "Your download links expire after 7 days. Create a free account to access your purchases anytime.",
      createAccount: "Create account",
      login: "Log in",
      backToShop: "← Back to shop",
      descriptionMeta: "Your order is confirmed — your download is ready.",
    },
    product: {
      free: "Free",
      inCart: "In cart",
      added: "Added!",
      addToCart: "Add to cart",
    },
    account: {
      loginHeading: "Login",
      registerHeading: "Register",
      dashboardHeading: "My Account",
      settingsHeading: "Account Settings",
      forgotHeading: "Forgot Password",
      resetHeading: "Reset Password",
      invalidLinkHeading: "Invalid Link",
      invalidLinkBody: "This reset link is invalid or has expired.",
      email: "Email",
      password: "Password",
      name: "Name",
      currentPassword: "Current Password",
      newPassword: "New Password",
      minChars: "Minimum 8 characters",
      changePassword: "Change Password (optional)",
      loggingIn: "Logging in...",
      login: "Login",
      forgotPassword: "Forgot your password?",
      noAccount: "No account yet?",
      register: "Register",
      alreadyAccount: "Already have an account?",
      creatingAccount: "Creating account...",
      createAccount: "Create account",
      myDownloads: "My Downloads",
      noPurchases: "No purchases yet.",
      visitShop: "Visit the shop →",
      download: "Download",
      comingSoon: "Coming soon",
      appSubscriptions: "App Subscriptions",
      appSubscriptionsBody: "Managing your app subscription? Subscriptions are handled directly through the App Store or Google Play. Visit the store where you purchased the app to manage or cancel your subscription.",
      settings: "Settings",
      logout: "Logout",
      backToDashboard: "← Back to Dashboard",
      saving: "Saving...",
      saveChanges: "Save Changes",
      changesSaved: "Changes saved.",
      sending: "Sending...",
      sendResetLink: "Send Reset Link",
      resetSent: "If an account exists for that email address, you'll receive a reset link shortly. Check your inbox.",
      backToLogin: "← Back to Login",
      resetting: "Saving...",
      setNewPassword: "Set New Password",
      passwordUpdated: "Password updated — redirecting to your account...",
      requestNewLink: "Request a new link →",
      tryAgain: "Please try again.",
      somethingWrong: "Something went wrong — try again.",
      resetHeadingInvalid: "Invalid Link",
    },
  },
} as const;

export function getStrings(locale: Locale) {
  return strings[locale];
}